### ISSUE TITLE
提几个命名小建议

### ISSUE THREAD

**Issue by aristotll** [ainilili/ourbatis#4]
1. 类名错误

https://github.com/ainilili/ourbatis/blob/2874ff30e6515179dcdbf2807dc2b7ba30c24083/src/main/java/org/nico/ourbatis/utils/ReflactUtils.java#L11

`ReflactUtils` 应该是 ReflectUtils

2. 

https://github.com/ainilili/ourbatis/blob/2874ff30e6515179dcdbf2807dc2b7ba30c24083/src/main/java/org/nico/ourbatis/utils/AssertUtils.java#L13

-> 这一般叫 assertNotNull 

https://github.com/ainilili/ourbatis/blob/2874ff30e6515179dcdbf2807dc2b7ba30c24083/src/main/java/org/nico/ourbatis/utils/AssertUtils.java#L27-L41

这个实现一般叫 assertNotEmpty

blank 一般是对 CharSequence 来说的 (可以参考 https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/Validate.java

**Comment by ainilili** [comment]
感谢，之后会重新审视下代码！
